(function(){
var f=true,h=null,i=false,k=navigator,aa=undefined,ba=encodeURIComponent,l=parseInt,m=window,n=document,p=Math;function ca(a,b){return a.toString=b}
var r="push",s="toString",t="valueOf",u="length",da="plugins",v="prototype",ea="round",w="slice",x="replace",y="document",z="split",fa="cookie",ga="charAt",A="userAgent",C="screen",D="indexOf",ha="domain",E="write",F="call",ia="random",G="getParameter",ja="referrer",H="substring",ka="apply",la="contentWindow",J="getTime",K="join",ma="toLowerCase",na=this,oa=function(a,b,c){var d=a[z]("."),e=c||na;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d[u]&&(g=d.shift());)if(!d[u]&&b!==aa)e[g]=
b;else e=e[g]?e[g]:(e[g]={})};p.floor(p[ia]()*2147483648)[s](36);var pa=function(a,b){var c=a.Y;if(arguments[u]>2){var d=Array[v][w][F](arguments,2);c&&d.unshift[ka](d,c);c=d}b=a.$||b;a=a.Z||a;var e,g=b||na;e=c?function(){var j=Array[v][w][F](arguments);j.unshift[ka](j,c);return a[ka](g,j)}:function(){return a[ka](g,arguments)};e.Y=c;e.$=b;e.Z=a;return e},L=function(a,b,c){oa(a,b,c)},qa=function(a,b){function c(){}c.prototype=b[v];a.la=b[v];a.prototype=new c};function ra(a,b){var c=parseFloat(a);return isNaN(c)||c>1||c<0?b:c}function sa(a,b){if(a=="true")return f;if(a=="false")return i;return b}function ta(a,b){var c=/^([\w-]+\.)+[\w-]{2,}(\:[0-9]+)?$/;return c.test(a)?a:b};var ua="pagead2.googlesyndication.com",va="googleads.g.doubleclick.net",wa="pubads.g.doubleclick.net",xa="securepubads.g.doubleclick.net",ya="partner.googleadservices.com",za=ta("pagead2.googlesyndication.com",ua);ta("googleads.g.doubleclick.net",va);ta("pagead2.googlesyndication.com",ua);var Aa=ta("pubads.g.doubleclick.net",wa),Ba=ta("partner.googleadservices.com",ya),Ca=ta("securepubads.g.doubleclick.net",xa);function M(a){return typeof ba=="function"?ba(a):escape(a)}function Da(a){if(a in Ea)return Ea[a];return Ea[a]=k[A][ma]()[D](a)!=-1}var Ea={};function Fa(){return Da("msie")&&!m.opera}
function Ga(){if(k[da]&&k.mimeTypes[u]){var a=k[da]["Shockwave Flash"];if(a&&a.description)return a.description[x](/([a-zA-Z]|\s)+/,"")[x](/(\s)+r/,".")}else if(k[A]&&k[A][D]("Windows CE")>=0){for(var b=3,c=1;c;)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=h}return b[s]()}else if(Fa()){c=h;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(e){b=0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=6;c.AllowScriptAccess="always"}catch(g){if(b==
6)return b[s]()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(j){}}if(c){b=c.GetVariable("$version")[z](" ")[1];return b[x](/,/g,".")}}return"0"}var Ha=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=m.history[u];a.u_java=k.javaEnabled();if(m[C]){a.u_h=m[C].height;a.u_w=m[C].width;a.u_ah=m[C].availHeight;a.u_aw=m[C].availWidth;a.u_cd=m[C].colorDepth}if(k[da])a.u_nplug=k[da][u];if(k.mimeTypes)a.u_nmime=k.mimeTypes[u]};var Ia={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Ja={google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",
google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},Ka=
{google_only_pyv_ads:"pyv",google_with_pyv_ads:"withpyv"};var La=n,N=k,O=m;
function Ma(){var a=La[fa],b=p[ea]((new Date)[J]()/1000),c=O.google_analytics_domain_name,d=typeof c=="undefined"?Na("auto"):Na(c),e=a[D]("__utma="+d+".")>-1,g=a[D]("__utmb="+d)>-1,j=a[D]("__utmc="+d)>-1,q,o={},B=!!O&&!!O.gaGlobal;if(e){q=a[z]("__utma="+d+".")[1][z](";")[0][z](".");o.sid=g&&j?q[3]+"":B&&O.gaGlobal.sid?O.gaGlobal.sid:b+"";o.vid=q[0]+"."+q[1];o.from_cookie=f}else{o.sid=B&&O.gaGlobal.sid?O.gaGlobal.sid:b+"";o.vid=B&&O.gaGlobal.vid?O.gaGlobal.vid:(p[ea](p[ia]()*2147483647)^Oa()&2147483647)+
"."+b;o.from_cookie=i}o.dh=d;o.hid=B&&O.gaGlobal.hid?O.gaGlobal.hid:p[ea](p[ia]()*2147483647);return O.gaGlobal=o}function Oa(){var a=La[fa]?La[fa]:"",b=O.history[u],c,d,e=[N.appName,N.version,N.language?N.language:N.browserLanguage,N.platform,N[A],N.javaEnabled()?1:0][K]("");if(O[C])e+=O[C].width+"x"+O[C].height+O[C].colorDepth;else if(O.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d[C].width+"x"+d[C].height}e+=a;e+=La[ja]?La[ja]:"";for(c=e[u];b>0;)e+=b--^c++;return Pa(e)}
function Pa(a){var b=1,c=0,d,e;if(!(a==aa||a=="")){b=0;for(d=a[u]-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function Na(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=La[ha];if("www."==a[H](0,4))a=a[H](4,a[u])}return Pa(a[ma]())};n.URL&&(n.URL[D]("?google_debug")>0||n.URL[D]("&google_debug")>0);function Va(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==h)this._domain_=n[ha]}ca(Va[v],function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"});function Wa(){this.v=Xa(this);this.L=i;if(!this.v)this.L=Ya(this)}Wa[v].K="__gads=";Wa[v].B="GoogleAdServingTest=";Wa[v].setCookieInfo=function(a){this.q=a._cookies_[0];if(this.q!=h){this.v=this.q._value_;Za(this)}};
var $a=function(a,b){var c=(new Date)[t](),d=new Date;d.setTime(c+b);return d},ab=function(a){var b=15552000000,c=$a(a,b),d="ID=12345:T="+b,e="/",g=n[ha];return new Va(d,c[t](),e,g)},bb="http://"+Ba+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo",cb=function(a,b){if(!(a.v||!a.L)){var c="script",d=n[ha],e=bb+"&client="+M(b)+"&domain="+M(d);n[E]("<"+c+' src="'+e+'"></'+c+">")}},Ya=function(a){n.cookie=a.B+"Good";var b=db(a,a.B),c=b=="Good";if(c){var d=$a(a,-1);n.cookie=a.B+"; expires="+
d.toGMTString()}return c},Xa=function(a){var b=db(a,a.K);return b},db=function(a,b){var c=n[fa],d=c[D](b),e="";if(d!=-1){var g=d+b[u],j=c[D](";",g);if(j==-1)j=c[u];e=c[H](g,j)}return e},Za=function(a){if(!(a.q==h))if(a.v){var b=new Date;b.setTime(1000*a.q._expires_);var c=a.q._domain_,d=a.K+a.v+"; expires="+b.toGMTString()+"; path="+a.q._path_+"; domain=."+c;n.cookie=d}};function eb(a,b){try{return a.top[y].URL==b.URL}catch(c){}return i};sa("false",i);sa("false",i);sa("false",i);var fb=sa("false",i),gb=m;var hb=function(a){this.X=(this.M=a&&a.GA_jstiming)&&this.M.load};hb[v].tick=function(a,b){this.X.tick(a,b)};hb[v].report=function(a){var b={};b.e=a;this.M.report(this.X,b)};var kb=function(){};qa(kb,hb);kb[v].tick=function(){};kb[v].report=function(){};var lb=function(a,b,c,d){if(c<=4){var e=b+"_"+c;d?a.tick(e,d+"_"+c):a.tick(e)}};var P=gb&&p[ia]()<ra("0.005",0.0010)&&gb.GA_jstiming&&gb.GA_jstiming.load&&gb.location.protocol=="http:"?new hb(gb):new kb(gb);P.tick("js_load");function Q(a){return typeof a=="function"}function mb(a,b){if(typeof a!="string"||a[u]==0)return h;else if(typeof b!="string"||b[u]==0)return h;return nb(R(),a,b)}L("GA_googleAddSlot",mb);function _GA_googleInitializeAdEngine(a){if(!S()){ob(pb(a));qb(S())}}L("_GA_googleInitializeAdEngine",_GA_googleInitializeAdEngine);
function rb(){R().ba=f;_GA_googleInitializeAdEngine(h);var a=S().h;a=="sync"||a=="sync_sra"?S().i():sb(R())}L("GA_googleFetchAds",rb);function tb(){_GA_googleInitializeAdEngine("iframe");cb(m._GA_googleCookieHelper,m.GS_googleGetIdsForAdSenseService())}L("GA_googleUseIframeRendering",tb);function ub(){var a=m.GA_googleEnv[G]("google_ad_impl");a==h&&m.GA_googleEnv.setParameter("google_ad_impl","sync_sra")}L("GA_googleUseSyncSRARendering",ub);
function vb(a){if(!(S()==h))if(!(S().h=="iframe")){if(wb(S()))if(S().J){var b=xb(R(),a);if(b==h)return;else if(!b._enabled_)return}else return;else if(yb(S(),a)!=h&&!S().k)return;S().n(a)}}L("GA_googleFillSlot",vb);function zb(a,b,c,d){a=a||"";b=b||"";c=c||0;d=d||0;if(!(S()==h))if(!(S().h!="iframe")){nb(R(),a,b);var e=new Ab(c,d,i,f);Bb(R(),b,e);S().n(b)}}L("GA_googleFillSlotWithSize",zb);function Cb(){Db(new Eb(Ia));ob(h)}L("GA_googleResetAll",Cb);m.google_noFetch=i;
function Fb(){m.google_noFetch=f}L("GA_googleNoFetch",Fb);function Gb(){m.google_delayFetch=f}L("GA_googleDelayFetch",Gb);function Ab(a,b,c,d){this._width_=a;this._height_=b;this._expandable_=c;this._enabled_=d}ca(Ab[v],function(){return"[GA_GoogleAdSlotAttr: width="+this._width_+", height="+this._height_+", expandable="+this._expandable_+", enabled="+this._enabled_+"]"});
function Hb(a){for(var b={},c=a[z]("?"),d=c[c[u]-1][z]("&"),e=0;e<d[u];e++){var g=d[e][z]("=");if(g[0])try{b[g[0][ma]()]=g[u]>1?m.decodeURIComponent?decodeURIComponent(g[1][x](Ib," ")):unescape(g[1]):""}catch(j){}}return b}function Jb(a){var b=a||n.URL;this.V=Hb(b)}Jb[v].getParameter=function(a){return a==h?h:this.V[a]};Jb[v].setParameter=function(a,b){this.V[a]=b};var Kb=function(a){if(!fb)return a?"http://"+Aa:"http://"+Ba;return"https://"+Ca};
function Lb(a){return a[x](/&/g,"&amp;")[x](/</g,"&lt;")[x](/>/g,"&gt;")[x](/\"/g,"&quot;")}function Mb(){this.D=h;this.W=i;this.ka=(new Date)[t]()}
var Ob=function(a,b){if(!(a.D!=h))if(!a.W){a.D=m.open("","GoogleAdCapture","width=1100, height=1400, status=no, resizable=yes, scrollbars=yes,menubar=yes, toolbar=yes");if(a.D){var c=a.D[y],d=[];d[r]('<html>\n<head>\n<title>Google Ad Capture Window</title>\n<script>function displayTime(id, start){var delta=(new Date()).valueOf() - start;document.getElementById(id).innerHTML=""+delta;}var pageStartTime = (new Date()).valueOf();var slotStartTime = 0;window.onload=function(){displayTime("total", pageStartTime);};<\/script></head>\n<body>\n');d[r]("<p>Google Ad Capture Window</p>");
for(var e in b)Q(b[e])||d[r](Nb(a,e,b[e]));d[r]("<p>Time blocked rendering ads (ms): <label id='blocked'></label>");d[r]("<script>displayTime('blocked', pageStartTime);<\/script>");d[r]("<p>Total Page Load Time (ms): <label id='total'></label>");d[r]("</body>\n</html>");var g=d[K]("\n"),j=m.GA_googleEnv[G]("google_capture_norender")!=h;j?c[E](Lb(g)):c[E](g);c.close()}else a.W=f}},Nb=function(a,b,c){var d="<script>slotStartTime = (new Date()).valueOf();<\/script>",e="<p>Slot "+b+"</p>",g;g=c==h||c._html_==
h?"No ad":c._html_;var j="<p>Slot Time (ms): <label id='"+b+"'></label>",q='<script>displayTime("'+b+'", slotStartTime);<\/script>';return d+e+"\n"+g+"\n"+j+q};function Pb(a){this.d={};this.C=a}var Qb=function(a,b,c,d){if(b){c||(c="");if(b=="google_gl")b="google_country";else if(b=="google_region")b="google_section";if(b in a.C)if((d=typeof d=="undefined"||d)||!a.d[b])a.d[b]=c}},Rb=function(a,b){for(var c in b.d)Q(b.d[c])||a.d[c]||(a.d[c]=b.d[c])};Pb[v].getAttribute=function(a){return this.d[a]};
Pb[v].g=function(){var a=[];for(var b in this.d)if(!Q(this.d[b])){var c=Ia[b]||Ja[b]||Ka[b]||h,d=this.d[b];c&&d&&a[r](c+"="+M(d))}return a[K]("&")};
var Tb=function(a,b,c,d){var e=Sb(a,b,c,d),g=[];e[0]&&e[0][u]>0&&g[r](e[0][K]("&"));e[1]&&e[1][u]>0&&g[r]("sps="+e[1][K]("|"));return g[K]("&")},Sb=function(a,b,c,d){var e=[],g=[],j=b.d;for(var q in d)if(!Q(q)){var o=d[q];if(o){var B="";if(j[q]!=h)B=M(j[q]);var I=[],ib=-1,Qa=-1;for(var Ra in a)if(!Q(a[Ra])){++ib;if(c[Ra]==h)I[r]("");else{var jb=c[Ra].d;if(jb[q]!=h){I[r](M(M(jb[q])));Qa=ib}else I[r]("")}}if(Qa>=0){var uc=M(B),Sa=[];Sa[r](uc);for(var Ta=0;Ta<=Qa;++Ta)Sa[r](I[Ta]);g[r](o+","+Sa[K](","))}else B&&
e[r](o+"="+B)}}var Ua=[];Ua[r](e);Ua[r](g);return Ua};function Ub(a,b){this.I=a;this.s=b;this.Q=0;this.ha=this.N=this.O=i;this.fa=this.ga=this.S=this.ca=h}var Vb=function(a){a.N=f;a.ca=(new Date)[t]()},Wb=function(a){a.S=(new Date)[t]()},Xb=function(a){a.ha=f;a.ga=(new Date)[t]()},Yb=function(a){a.fa=(new Date)[t]()};ca(Ub[v],function(){return"[GA_GoogleAdSlot: pubid="+this.I+", name="+this.s+", loaded="+this.O+", tries="+this.Q+"]"});
function Eb(a){this.a={};this.c=[];this.r={};this.C=a;this.U=new Pb(this.C);this.A={};this.ba=i;this.o=h}
var nb=function(a,b,c){var d=new Ub(b,c);return a.a[d.s]=d},Zb=function(a,b){var c=[];for(var d in a.a)if(!Q(a.a[d])){if(b){var e=xb(a,d);if(e==h||!e._enabled_)continue}var g=a.a[d];g.N||c[r](g)}return c},$b=function(a,b){return Zb(a,b)[u]},ac=function(a){var b=[];for(var c in a.a){var d=a.a[c];Q(d)||d.N&&d.S==h&&b[r](c)}return b},bc=function(a){var b=0;for(var c in a.a)if(!Q(a.a[c])){var d=xb(a,c);d!=h&&d._enabled_&&b++}return b},cc=function(a){for(var b in a.a)if(!Q(a.a[b])){var c=a.a[b];Vb(c)}},
dc=function(a,b){var c=a.a[b];Vb(c)},ec=function(a,b){var c=a.a[b];Wb(c)},fc=function(a,b){var c=a.a[b];Xb(c)},T=function(a,b){var c=a.a[b];Yb(c);lb(P,"ga_render",a.c[u],"ga_srt")},gc=function(a){var b=0;for(var c in a.a)Q(a.a[c])||b++;return b};ca(Eb[v],function(){var a="[AdData:",b=[];for(var c in this.a)Q(this.a[c])||b[r](this.a[c][s]());for(var d in this.r)Q(this.r[d])||b[r]("["+d+","+this.r[d]+"]");a+=b[K]();a+="]";return a});
var hc=function(a,b){return a.a[b]},ic=function(a,b,c){if(!(b==h||b[u]==0)){if(c==h||c[u]==0)c="";var d=a.r[b];a.r[b]=d==h?c:d+","+c}};function jc(a,b){ic(R(),a,b)}L("GA_googleAddAttr",jc);var kc=function(a,b,c){Qb(a.U,b,c)};function lc(a,b){kc(R(),a,b)}L("GA_googleAddAdSensePageAttr",lc);var mc=function(a){return a.U},nc=function(a,b,c,d){if(!(b==h||b[u]==0)){if(S()==h||S().h!="iframe"){var e=a.a[b];if(e==h)return}var g=a.A[b];if(g==h)a.A[b]=new Pb(a.C);Qb(a.A[b],c,d)}};
function oc(a,b,c){nc(R(),a,b,c)}L("GA_googleAddAdSenseSlotAttr",oc);var pc=function(a,b){return a.A[b]},qc=function(a){var b=Kb(a.google_new_gam_domain_enabled);return b+"/gampad/slotdata.js?callback=GA_googleSetAdSlotAttributes"},sb=function(a){if(a.o!=h)S().i();else{var b=[];for(var c in a.a)Q(a.a[c])||b[r](c);var d=m.GS_googleGetIdsForAdSenseService(),e=qc(m)+"&client="+escape(d)+"&page_slots="+escape(b[K]());n[E]("<script src = '"+e+"'><\/script>")}};
Eb[v].setAdSlotAttributes=function(a){this.o=a;S().J=f;S().i()};function rc(a){R().setAdSlotAttributes(a)}L("GA_googleSetAdSlotAttributes",rc);var Bb=function(a,b,c){if(a.o==h)a.o={};a.o[b]=c;S().J=f},xb=function(a,b){return a.o!=h?a.o[b]:h};function sc(a,b){this.ma=a;this.aa=b}function tc(a,b){this.AdSlotContent=sc;this.AdSlotConent(tc.HTML_TYPE,a);this._html_=b}ca(tc[v],function(){return"[GA_HTMLAdSlotContent expandable="+this.aa+", html="+this._html_+"]"});tc.prototype=new sc(tc.HTML_TYPE,i);
function vc(a,b,c){if(!c||c<0||c>1)c=0;this.ia=p[ia]()<c;this.da=a;this.R=b+"/pagead/gen_204?id="+M(a);this.ea=[]}var U=function(a,b,c){if(b&&b.match(/^\w+$/)&&c)a.R+="&"+b+"="+M(c)},wc=function(a){var b=R();for(var c in b.a){var d=b.a[c];if(!Q(d)&&d.I!=h){U(a,"pub_id",d.I);break}}U(a,"nslots",gc(b)[s]());U(a,"pub_url",n.URL);U(a,"pub_ref",n[ja])},xc=function(a){if(!a.ia||!a.da||!a.R)return i;var b=new Image;b.src=a.R;a.ea[r](b);return f};
function V(a){this.f=h;this.o={};this.p=this.b="";this.k=a;this.l=this.H=this.t=i;this.h="sync";this.ja=Ia;this.u=f;this.J=i;this.P=m.google_new_gam_domain_enabled}
var qb=function(a){a.t=m.GA_googleEnv[G]("google_nofetch")!=h||m.google_noFetch;a.H=m.GA_googleEnv[G]("google_norender")!=h;a.l=m.GA_googleEnv[G]("google_capture")!=h||m.GA_googleEnv[G]("google_capture_norender")!=h;if(a.l)a.H=f;yc(a,m);a.b=a.p;var b=pa(a.T,a);zc(a,m,b)},zc=function(a,b,c){if(b.attachEvent){b.attachEvent("onload",c);return f}if(b.addEventListener){b.addEventListener("load",c,i);return f}return i};V[v].F=function(){this.l&&Ob(m.GA_googleAdCapture,this.f)};
var Ac=function(a){if(a.h=="sync_sra"){var b=R(),c=gc(b),d=b.c[u];if(c!=d){a.G=new vc("sra_mismatch",Kb(a.P),ra("0.001",0.0010));U(a.G,"correlator",a.m);U(a.G,"fslots",d[s]());wc(a.G);xc(a.G)}}},Bc=function(a){P.tick("ga_onload");P.report(a.h)},Cc=function(a){var b=ac(R());if(b[u]>0){a.z=new vc("missing_cb",Kb(a.P),ra("0.01",0.0010));U(a.z,"pending",b[K]());U(a.z,"correlator",a.m);U(a.z,"impl",a.h);wc(a.z);xc(a.z)}};
V[v].T=function(){Bc(this);this.F();Ac(this);Cc(this)};var yc=function(a){var b=m.GA_googleEnv[G]("google_ad_url");if(b==h||b[u]==0)a.p=Kb(a.P)+"/gampad/ads?";else{if(b[ga](b[u]-1)!="?")b+="?";a.p=b}};V[v].j=function(){};
var yb=function(a,b){return a.f!=h?a.f[b]:h},Dc=function(){var a=k[A],b=a[D]("MSIE ");return b==-1?0:parseFloat(a[H](b+5,a[D](";",b)))},Ib=/\+/g,Ec=function(a,b){b=b[ma]();if(b[H](0,3)!="ca-")b="ca-"+b;return b},X=function(a,b,c){c!=h&&W(a,b,M(c[s]()))},W=function(a,b,c){if(c!=h)a.b+=a.b[ga](a.b[u]-1)!="?"?"&"+b+"="+c:b+"="+c},Fc=function(a,b){for(var c=Zb(R(),a.u),d=[],e=[],g=[],j=c[u],q=0;q<j;q++){var o=c[q];g[r](o.s);if(!(b!=h&&b!=o.s)){d[r](o.s);e[r](Ec(a,o.I))}}X(a,"client",e[0]);if(a.k)g[u]>
0&&X(a,"page_slots",g[K]());else{X(a,"slotname",d[K]());R().c[u]>0&&X(a,"page_slots",R().c[K]())}},Gc=function(a,b,c){if(c!=h){var d=b.lastIndexOf("?"),e=b[D]("google_preview=",d),g=b[D]("&",e);if(g==-1){g=b[u]-1;e-=1}return b[H](0,e)+b[H](g+1,b[u])}return b},Hc=function(a,b,c){if(eb(b,c))return c.URL;return c[ja]},Jc=function(a,b,c){if(Ic(a,b,c)!=c.URL)return c[ha];return""},Ic=function(a,b,c){var d=mc(R()).getAttribute("google_page_url");if(d)return d;return Hc(a,b,c)},Kc=function(a,b,c,d){X(a,
"url",Gc(a,Ic(a,m,n),m.GA_googleEnv[G]("google_preview")));X(a,"ref",n[ja]);X(a,"lmt",(Date.parse(n.lastModified)/1000)[s]());W(a,"dt",b[J]());if(n.body){var e=n.body.scrollHeight,g=n.body.clientHeight;g&&e&&X(a,"cc",p[ea](g*100/e)[s]())}var j=m.GA_googleEnv[G]("deb");j!=h&&X(a,"deb",j);var q=m.GA_googleEnv[G]("haonly");q!=h&&X(a,"haonly",q);var o=mc(R());k[A][D]("MSIE ")>0&&Qb(o,"google_encoding",n.charset,i);var B="";if(d)B=Tb(R().a,o,R().A,a.ja);else{var I=pc(R(),c);if(I==h)I=o;else Rb(I,o);B=
I.g()}if(B)a.b+="&"+B},Lc=function(a,b,c){var d=R().r,e=[];for(var g in d)Q(d[g])||e[r](M(g)+"="+M(d[g]));X(a,"cust_params",e[K]("&"));if(b._GA_googleCookieHelper){X(a,"cookie",b._GA_googleCookieHelper.v);b._GA_googleCookieHelper.L&&X(a,"cookie_enabled","1")}b.google_new_gam_domain_checked==1&&b.google_new_gam_domain_enabled!=1&&W(a,"dblk",1);var j=Jc(a,b,c);j&&X(a,"cdm",j)},Mc=function(a){Ma();var b=m;W(a,"ga_vid",b.gaGlobal.vid);W(a,"ga_sid",b.gaGlobal.sid);W(a,"ga_hid",b.gaGlobal.hid);W(a,"ga_fc",
b.gaGlobal.from_cookie);X(a,"ga_wpids",b.google_analytics_uacct)},Nc=function(a,b){for(var c in b)W(a,c,b[c])};V[v].g=function(a){this.j();var b=new Date;Fc(this,a);Lc(this,m,n);m.GA_googleEnv[G]("google_preview")!=h&&W(this,"gct",m.GA_googleEnv[G]("google_preview"));Mc(this);Kc(this,b,a,this.k);var c={};Ha(c);Nc(this,c);W(this,"flash",Ga());this.b=this.b[H](0,2000);return this.b=this.b[x](/%\w?$/,"")};
var Oc="google_ads_iframe_"[u],wb=function(a){return a.u},Pc=function(a,b){var c=b.getAttribute("id"),d=c.substr(Oc,c[u]-Oc);return d},Qc=function(a,b,c,d,e,g,j){var q="google_ads_iframe_"+b,o=[];if(j){var B="google_ads_div_"+b;o[r]("<div id=",B,">")}o[r]("<iframe id=",q," name=",q,' width="',e,'" height="',g,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",a.l?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" style="border:0px;"',' src="',Lb(c),'"');d!=h&&o[r](' onload="',
d,'"');o[r]("></iframe>");j&&o[r]("</div>");var I=o[K]("");n[E](I)};
V[v].createDOMIframe=function(a,b){var c=yb(this,b),d=c._width_,e=c._height_,g=c._html_,j=n.createElement("iframe");j.id="google_ads_iframe_"+b;j.name="google_ads_iframe_"+b;j.width=d;j.height=e;j.vspace=0;j.hspace=0;j.allowTransparency="true";j.scrolling="no";j.marginWidth=0;j.marginHeight=0;j.frameBorder=0;j.style.border=0;var q=n.getElementById(a);q.appendChild(j);if(this.l){j[la][y][E](Lb(g));j.scrolling="auto"}else j[la][y][E](g);j[la][y].close();T(R(),b)};
function Rc(a,b){S().createDOMIframe(a,b)}L("GA_googleCreateDomIframe",Rc);
var Sc=function(){var a=[],b=n.getElementsByTagName("base");if(b)for(var c=0,d=b[u];c<d;++c){var e=b[c],g=e.getAttribute("target");if(g){a[r]({baseElement:e,originalTagValue:g});e.removeAttribute("target")}}return a},Tc=function(a){if(a)for(var b=0,c=a[u];b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}},Uc=function(a){var b="http://"+za+"/pagead/inject_object_div.js";if(l(Dc(),10)>6)return i;if(a[D](b)<0)return i;return f},Vc=function(a,b,c){if(a.l)c=Lb(c);var d=Sc();
m.frames[b.name].contents=c;b.src=Uc(c)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';Tc(d)},Wc=function(a,b,c){var d=Pc(a,b),e=b[la]?b[la][y]:b.contentDocument;if(e==h)if(n.implementation&&n.implementation.createDocument)e=n.implementation.createDocument("",d,h);else if(typeof ActiveXObject!="undefined")e=new ActiveXObject("Msxml.DOMDocument");else return;e.open("text/html","replace");a.l?e[E](Lb(c)):e[E](c);e.close()},Xc=function(a,b){var c=Pc(a,
b),d=hc(R(),c);if(!d.O){d.O=f;var e=yb(a,c),g=b.parentNode;if(e==h||e._html_==h){g.removeChild(b);T(R(),c)}else if(e._expandable_){g.innerHTML=e._html_;T(R(),c)}else{e._is_3pas_?Vc(a,b,e._html_):Wc(a,b,e._html_);T(R(),c)}}},Yc=function(a,b){var c="google_ads_div_"+b,d="<div id="+c+">",e=yb(a,b);if(!(e==h)){d+=e._html_;d+="\n</div>\n";n[E](d);T(R(),b)}},Zc=function(a,b){var c="google_ads_div_"+b,d="<div id="+c+">";d+="\n</div>\n";n[E](d);return c},$c=function(a){if(!a.u)return f;if($b(R(),a.u)>0)return f;
else if(bc(R())==0)return i};V[v].setAdContentsBySlot=function(a){lb(P,"ga_srt",R().c[u],"_ga_start");if(this.f==h){this.f=a;for(var b in a)Q(a[b])||ec(R(),b)}else for(b in a)if(!Q(a[b])){this.f[b]=a[b];ec(R(),b)}var c=i;for(b in a)if(!Q(a[b])){var d=a[b];if(c){d._cookies_=[ab(m._GA_googleCookieHelper)];c=i}d!=h&&d._cookies_!=h&&m._GA_googleCookieHelper.setCookieInfo(d)}};function ad(a){S().setAdContentsBySlot(a)}L("GA_googleSetAdContentsBySlot",ad);
function Y(a){V[F](this,a);this.u=i;this.m=(new Date)[J]();this.h=a?"sync_sra":"sync"}qa(Y,V);Y[v].j=function(){this.b=this.p;X(this,"correlator",this.m[s]());W(this,"output","json_html");W(this,"callback","GA_googleSetAdContentsBySlotForSync");this.k?W(this,"impl","ss"):W(this,"impl","s");var a=0,b=f;for(var c in this.f)if(!Q(this.f[c])){var d=this.f[c];if(d._is_afc_==aa){b=i;break}else a=2*a+(d._is_afc_?1:0)}b&&W(this,"prev_afc",a);this.k||bd(this,R().c,this.f)};
var bd=function(a,b,c){if(b&&c){for(var d=[],e=[],g=b[u]-1,j=0;j<g;j++){var q=b[j],o=c[q];if(o&&o._cids_&&o._a2ids_){d[r](o._cids_[0]);e[r](o._a2ids_[0])}else{d[r]("");e[r]("")}}if(d[u]>0){var B=d[K](","),I=e[K](",");X(a,"a2ids",I);X(a,"cids",B)}}},cd=function(a,b){var c=R().a,d=c[b];if(!(d==h))if(!a.t){a.g(d.s);dc(R(),b);n[E]("<script src = '"+a.b+"'><\/script>")}};
Y[v].setAdContentsBySlotForSync=function(a){this.setAdContentsBySlot(a);if(this.k)if(R().c[u]==1){var b=R().c[0];dd(this,b);return}for(var c in a)Q(a[c])||dd(this,c)};function ed(a){S().setAdContentsBySlotForSync(a)}L("GA_googleSetAdContentsBySlotForSync",ed);Y[v].i=function(){$c(this)};var fd=function(a){a.g(h);n[E]("<script src = '"+a.b+"'><\/script>");cc(R())};Y[v].n=function(a){R().c[r](a);lb(P,"_ga_start",R().c[u]);if(this.k)R().c[u]==1?fd(this):dd(this,a);else cd(this,a)};
var gd=function(a,b,c){if(b.google_js_backfill){var d="script";c[E]("<"+d+' src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></'+d+">")}},dd=function(a,b){hd(a,m,n,b)},hd=function(a,b,c,d){var e=hc(R(),d);if(!(e==h)){var g=yb(a,d);fc(R(),d);if(g==h||g._empty_){gd(a,b,c,d);T(R(),d)}else if(a.H&&!a.l)T(R(),d);else if(g._snippet_&&!g._is_afc_&&!a.l)Yc(a,d);else if(k[A][D]("MSIE ")>0){var j="GA_googleSyncAdSlotLoaded(this);";Qc(a,d,"about:blank",j,g._width_,g._height_,f)}else{var q=Zc(a,
d);c[E]("<script>GA_googleCreateDomIframe('"+q+"' ,'"+d+"');<\/script>")}}};Y[v].syncAdSlotLoaded=function(a){var b=Pc(this,a);hc(R(),b);Xc(this,a)};function id(a){S().syncAdSlotLoaded(a)}L("GA_googleSyncAdSlotLoaded",id);function Z(a){V[F](this,a);this.m=(new Date)[J]();this.h="async"}qa(Z,V);Z[v].j=function(){this.b=this.p;jd(this);X(this,"correlator",this.m[s]());W(this,"output","json_html");W(this,"callback","GA_googleSetAdContentsBySlot");W(this,"impl","a")};
var jd=function(a){a.delay=500;var b=m.GA_googleEnv[G]("google_async_delay");if(b!=h)a.delay=1000*b};Z[v].i=function(){if($c(this))this.t||m.setTimeout("GA_googleReallyFetchAds();",this.INITIAL_ASYNC_DELAY)};
Z[v].reallyFetchAds=function(){if(!($b(R(),this.u)==0)){var a=n.getElementsByTagName("head")[0];if(this.k){var b=n.createElement("script");b.src=this.g(h);a.appendChild(b);cc(R())}else{var c=R().a;for(var d in c)if(!Q(c[d])){b=n.createElement("script");b.src=this.g(d);a.appendChild(b);dc(R(),d)}}}};function kd(){S().reallyFetchAds()}L("GA_googleReallyFetchAds",kd);
Z[v].n=function(a){var b=hc(R(),a);if(!(b==h)){R().c[r](a);var c="GA_googleAsyncAdSlotLoaded(this);",d=xb(R(),a);Qc(this,a,"about:blank",c,d._width_,d._height_,f)}};Z[v].asyncAdSlotLoaded=function(a){var b=Pc(this,a);hc(R(),b);!this.t&&!this.H&&ld(this,a)};function md(a){S().asyncAdSlotLoaded(a)}L("GA_googleAsyncAdSlotLoaded",md);var ld=function(a,b){var c=Pc(a,b),d=hc(R(),c);if(a.f==h||a.f[c]==h){if(!(d.Q>30)){m.setTimeout(function(){ld(S(),b)},a.delay);d.Q++}}else Xc(a,b)};Z[v].F=function(){};
function $(a){V[F](this,a);this.m=(new Date)[J]();this.h="fallback"}qa($,V);$[v].j=function(){this.b=this.p;X(this,"correlator",this.m[s]());W(this,"output","html");W(this,"impl","fb")};$[v].i=function(){$c(this)};$[v].w=function(a){var b;if(this.k){this.g(h);b=this.b+"&currentslot="+M(a)}else b=this.g(a);return b};$[v].n=function(a){var b=xb(R(),a);if(!(b==h)){R().c[r](a);if(!this.t){var c=this.w(a);Qc(this,a,c,h,b._width_,b._height_,f)}}};
function nd(a){V[F](this,a);this.m=(new Date)[J]();this.J=f;this.h="iframe"}qa(nd,V);nd[v].j=function(){this.b=this.p;X(this,"correlator",this.m[s]());W(this,"output","html");W(this,"impl","ifr")};nd[v].i=function(){$c(this)};nd[v].w=function(a){var b;if(this.k){this.g(h);b=this.b+"&currentslot="+M(a)}else b=this.g(a);return b};nd[v].n=function(a){var b=xb(R(),a);if(!(b==h)){R().c[r](a);if(!this.t){var c=this.w(a);Qc(this,a,c,h,b._width_,b._height_,f)}}};
var od=function(){if(Fa()){var a=Dc();return a<=5}else if(Da("firefox")){var b=k[A][D]("Firefox")+8,c=l(k[A][ga](b),10),d=k[A][w](b);return c<1}else if(Da("safari")){b=k[A][D]("Safari")+7;d=k[A][w](b);var e=l(d,10);return e<412}else if(m.opera!=h){b=k[A][D]("Opera")+6;d=k[A][w](b);c=l(d,10);return c<9}else if(!Fa()&&!Da("safari")&&Da("mozilla")){b=k[A][D]("Netscape")+9;d=k[A][w](b);c=l(d,10);return c<7}else return f},pd=function(){if(Fa()){var a=Dc();return a>5}else if(Da("firefox")){var b=k[A][D]("Firefox")+
8,c=l(k[A][ga](b),10);k[A][w](b);return c>1}return i},qd=function(){if(od())return"fallback";else if(m.google_delayFetch&&pd())return"async";return"sync"},pb=function(a){var b=h;if(typeof a!="undefined"&&a!=h)b=a;else{b=m.GA_googleEnv[G]("google_ad_impl");if(b==h)b=qd()}switch(b){case "async":return new Z(i);case "sync":return new Y(i);case "sync_sra":return new Y(f);case "fallback":return new $(i);case "iframe":return new nd(i);default:return new $(i)}},rd;
function R(){rd||(rd=new Eb(Ia));return rd}function Db(a){delete rd;rd=a}var sd;function S(){sd||(sd=h);return sd}function ob(a){delete sd;sd=a}if(typeof m.GA_googleEnv=="undefined")m.GA_googleEnv=new Jb;if(typeof m.GA_googleAdCapture=="undefined")m.GA_googleAdCapture=new Mb;if(m._GA_googleCookieHelper==h)m._GA_googleCookieHelper=new Wa;P.tick("js_parse","js_load");P.tick("jl");
})()
