<html xmlns="http://www.w3.org/1999/xhtml"
  xmlns:svg="http://www.w3.org/2000/svg"
  xmlns:xul="http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"
>
	<head>
	</head>
	<body>
		<svg xmlns="http://www.w3.org/2000/svg"
		     xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" zoomAndPan="disable" >

			<?= $this->js('/prototype.js'); ?>
			<?= $this->js('/scriptaculous/scriptaculous.js'); ?>

			<?= $this->layout()->content ?>
		</svg>
	</body>
</html>