<?= $this->doctype('XHTML1_STRICT') ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
	 <head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="Content-Language" content="en" />
		<meta http-equiv="Content-style-type" content="text/css" />

		<meta name="rating" content="general" />
		<meta name="robots" content="index,follow" />

		<title>SVG Game</title>
	</head>

	<body>

		<div id="layout_container">
			<div id="layout_header">
				<?= $this->action('header', 'Layout') ?>
			</div>

			<div id="layout_wrapper">

				<div id="pageminheight">
				</div>

				<div id="layout_content">
					<?= $this->layout()->content ?>
				</div>

			</div>
			<div id="layout_footer">
				<?= $this->action('footer', 'Layout') ?>
			</div>
		</div>

	</body>
</html>