<svg
	xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
	xmlns:svg="http://www.w3.org/2000/svg"
	xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
	xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
	sodipodi:version="0.32"
	inkscape:version="0.46"
	sodipodi:docname="big.svg"
	inkscape:output_extension="org.inkscape.output.svg.inkscape"
    xml:space="preserve"
    zoomAndPan="enable"
    width="100%"
    height="100%" >

	<?= $this->js('/prototype.js'); ?>
	<?= $this->js('/irlig/base.js'); ?>

	<?= $this->layout()->content ?>

</svg>