<!-- Here comes the night -->
<rect
   style="fill:url(#radialGradient6198);stroke:none;"
   fill-opacity="1"
   id="sunlight"
   width="100%"
   height="100%"
/>

<?= $this->js('/irlig/init.js'); ?>
<?= $this->js('/irlig/anim.js'); ?>
<?= $this->js('/irlig/ground.js'); ?>
<?= $this->js('/irlig/hud.js'); ?>
<?= $this->js('/irlig/player.js'); ?>

<?= $this->js('/astar.js'); ?>

<?= $this->css('/game.css', 'media', 'style') ?>
<?= $this->css('/map_'.$this->mapName.'.css', 'media', 'style') ?>

<?= $this->map($this->mapName) ?>

<defs>

    <linearGradient
       id="linear_radial_mask">
      <stop
         style="stop-color:#ffffff;stop-opacity:0;"
         offset="0"
         id="stop6194" />
      <stop
         id="stop6200"
         offset="0.27000001"
         style="stop-color:#000000;stop-opacity:0;" />
      <stop
         style="stop-color:#000000;stop-opacity:1;"
         offset="1"
         id="stop6196" />
    </linearGradient>
    <radialGradient
       inkscape:collect="always"
       xlink:href="#linear_radial_mask"
       id="radial_mask"
       cx="640"
       cy="400"
       fx="640"
       fy="400"
       r="640"
       gradientTransform="matrix(1,0,0,0.625,0,150)"
       gradientUnits="userSpaceOnUse" />
    <pattern id="pavement" width="512" height="512" patternUnits="userSpaceOnUse">
	    <image xlink:href="/resources/images/stone_pavement.png" x="0" y="0" width="512" height="512"/>
	</pattern>

	<?= $this->element('buddy', 'character') ?>

	<? foreach (array( 'medium_grass', 'big_tree', 'plane_grass', 'nicubunu_RPG_map_symbols_Crossroads_Sign' ) as $e) : ?>
		<?= $this->element( $e, 'map_element') ?>
	<? endforeach; ?>
</defs>

<?= ''/* ALWAYS LAST !  $this->partial('hud.svg'); */ ?>

<script>

	IRL_IG.init('<?= $this->mapName ?>', <?= $this->jsMatrix; ?>);

</script>

